spring.profiles.default=h2
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.mvc.problemdetail.enabled=true
spring.security.filter.dispatcher-types=REQUEST,ASYNC,ERROR
# pooled-lo uses the next sequence as the lower bound, which to me is more intuitive
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=pooled-lo
app.security.jwt.secret=ThisIsADemoJwtSecretKeyForInterviewProjectNeedsToBeLongEnough12345
app.security.jwt.access-token-ttl=PT15M
